name: Alert

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://born-to-llama.herokuapp.com/refresh
    - name: Deploy Stage
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'DefiLlama',
            repo: 'defillama-server',
            workflow_id: 'workflows/backend.yaml',
            ref: 'master',
          });
